### PR TITLE
host postgres error

### PR DESCRIPTION
**Pull request by soumyasaswata**
host postgres error while docker run

### CODE REVIEW

**Comment by slyapustin** [comment]
Hi @soumyasaswata.
Thank you for your contribution. Can you provide more information about the issue you have?
It should work well with the default Postgres DB created in the Docker container:
https://github.com/slyapustin/django-polls-elasticsearch/blob/ff28b9f33a72d8df864508a1dcac190de20f9d4f/app/project/settings.py#L83

**Comment by soumyasaswata** [comment]
It was giving error:

django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known

**Comment by slyapustin** [comment]
@soumyasaswata Can you try to build it from scratch to see if you have the same error?

**Comment by slyapustin** [comment]
@soumyasaswata It works well for me locally, so I'm going to close that PR.
Feel free to create an issue with full log and reproducible steps.

**Pull request closed without merging**
